# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_product.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(572, 528)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_delete_w = QtWidgets.QPushButton(Form)
        self.pb_delete_w.setMinimumSize(QtCore.QSize(0, 30))
        self.pb_delete_w.setMaximumSize(QtCore.QSize(300, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pictures/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_delete_w.setIcon(icon)
        self.pb_delete_w.setObjectName("pb_delete_w")
        self.gridLayout.addWidget(self.pb_delete_w, 6, 2, 1, 1)
        self.le_name = QtWidgets.QLineEdit(Form)
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 1, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 1, 1, 1)
        self.pb_add_w = QtWidgets.QPushButton(Form)
        self.pb_add_w.setMinimumSize(QtCore.QSize(0, 30))
        self.pb_add_w.setMaximumSize(QtCore.QSize(300, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../pictures/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_add_w.setIcon(icon1)
        self.pb_add_w.setObjectName("pb_add_w")
        self.gridLayout.addWidget(self.pb_add_w, 6, 1, 1, 1)
        self.pb_add_t = QtWidgets.QPushButton(Form)
        self.pb_add_t.setMinimumSize(QtCore.QSize(0, 30))
        self.pb_add_t.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pb_add_t.setIcon(icon1)
        self.pb_add_t.setObjectName("pb_add_t")
        self.gridLayout.addWidget(self.pb_add_t, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.le_total = QtWidgets.QLineEdit(Form)
        self.le_total.setEnabled(True)
        self.le_total.setObjectName("le_total")
        self.gridLayout.addWidget(self.le_total, 11, 2, 1, 1)
        self.le_size = QtWidgets.QLineEdit(Form)
        self.le_size.setObjectName("le_size")
        self.gridLayout.addWidget(self.le_size, 3, 0, 1, 3)
        self.pb_delete_wh = QtWidgets.QPushButton(Form)
        self.pb_delete_wh.setMinimumSize(QtCore.QSize(0, 30))
        self.pb_delete_wh.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pb_delete_wh.setIcon(icon)
        self.pb_delete_wh.setObjectName("pb_delete_wh")
        self.gridLayout.addWidget(self.pb_delete_wh, 4, 2, 1, 1)
        self.pb_delete_t = QtWidgets.QPushButton(Form)
        self.pb_delete_t.setMinimumSize(QtCore.QSize(0, 30))
        self.pb_delete_t.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pb_delete_t.setIcon(icon)
        self.pb_delete_t.setObjectName("pb_delete_t")
        self.gridLayout.addWidget(self.pb_delete_t, 8, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.pb_add_wh = QtWidgets.QPushButton(Form)
        self.pb_add_wh.setMinimumSize(QtCore.QSize(0, 30))
        self.pb_add_wh.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pb_add_wh.setIcon(icon1)
        self.pb_add_wh.setObjectName("pb_add_wh")
        self.gridLayout.addWidget(self.pb_add_wh, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.tw_t = QtWidgets.QTableWidget(Form)
        self.tw_t.setObjectName("tw_t")
        self.tw_t.setColumnCount(0)
        self.tw_t.setRowCount(0)
        self.gridLayout.addWidget(self.tw_t, 9, 0, 1, 3)
        self.pb_save = QtWidgets.QPushButton(Form)
        self.pb_save.setMaximumSize(QtCore.QSize(300, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../pictures/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_save.setIcon(icon2)
        self.pb_save.setObjectName("pb_save")
        self.gridLayout.addWidget(self.pb_save, 12, 2, 1, 1)
        self.tw_w = QtWidgets.QTableWidget(Form)
        self.tw_w.setObjectName("tw_w")
        self.tw_w.setColumnCount(0)
        self.tw_w.setRowCount(0)
        self.gridLayout.addWidget(self.tw_w, 7, 0, 1, 3)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tw_wh = QtWidgets.QTableWidget(Form)
        self.tw_wh.setObjectName("tw_wh")
        self.tw_wh.setColumnCount(0)
        self.tw_wh.setRowCount(0)
        self.gridLayout.addWidget(self.tw_wh, 5, 0, 1, 3)
        self.pb_add_photo = QtWidgets.QPushButton(Form)
        self.pb_add_photo.setMinimumSize(QtCore.QSize(0, 30))
        self.pb_add_photo.setMaximumSize(QtCore.QSize(200, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../pictures/photo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_add_photo.setIcon(icon3)
        self.pb_add_photo.setObjectName("pb_add_photo")
        self.gridLayout.addWidget(self.pb_add_photo, 1, 2, 1, 1)
        self.le_error = QtWidgets.QLineEdit(Form)
        self.le_error.setEnabled(False)
        self.le_error.setObjectName("le_error")
        self.gridLayout.addWidget(self.le_error, 13, 0, 1, 3)
        self.le_cost_price = QtWidgets.QLineEdit(Form)
        self.le_cost_price.setEnabled(False)
        self.le_cost_price.setObjectName("le_cost_price")
        self.gridLayout.addWidget(self.le_cost_price, 11, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 10, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb_delete_w.setText(_translate("Form", "Удалить  "))
        self.label_5.setText(_translate("Form", "Инструменты"))
        self.label_6.setText(_translate("Form", "Себестоимость:"))
        self.pb_add_w.setText(_translate("Form", "Добавить  "))
        self.pb_add_t.setText(_translate("Form", "Добавить   "))
        self.label_4.setText(_translate("Form", "Работы:"))
        self.le_total.setText(_translate("Form", "0"))
        self.pb_delete_wh.setText(_translate("Form", "Удалить "))
        self.pb_delete_t.setText(_translate("Form", "Удалить   "))
        self.label_3.setText(_translate("Form", "Элементы склада:                                              "))
        self.pb_add_wh.setText(_translate("Form", "Добавить "))
        self.label_2.setText(_translate("Form", "Габариты:"))
        self.pb_save.setText(_translate("Form", "Сохранить"))
        self.label.setText(_translate("Form", "Название:"))
        self.pb_add_photo.setText(_translate("Form", "Добавить фотографию"))
        self.le_cost_price.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", "Итого:"))
